tag 에러로 SERVICE_NAME 수정 10

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -99,6 +99,11 @@ jobs:
           echo "$SERVICE_NAME"
           echo "$LOCAL_IMAGE_NAME"
 
+          if ! docker image inspect "$LOCAL_IMAGE_NAME" > /dev/null 2>&1; then
+           echo "Error: Local image $LOCAL_IMAGE_NAME not found."
+            exit 1
+          fi
+
           docker tag "${LOCAL_IMAGE_NAME}" "${PUSH_IMAGES}"
           
           docker push "${PUSH_IMAGES}"
